site_name: Saltbox Documentation
site_url: https://docs.saltbox.dev/
site_author: salty
site_description: Saltbox is an Ansible-based solution for rapidly deploying a Docker containerized cloud media server.

repo_name: Saltbox
repo_url: https://github.com/saltyorg/docs

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    
plugins:
  - search:
      lang: en

extra:
  generator: false
  social:
  - icon: fontawesome/solid/heart
    link: 'https://github.com/saltyorg/Saltbox/blob/master/DONATIONS.md'
    name: Donate
  - icon: fontawesome/brands/discord
    link: 'https://discord.saltbox.dev'
    name: Discord
  - icon: fontawesome/brands/github
    link: 'https://github.com/saltyorg/Saltbox'
    name: GitHub
  analytics:
    provider: google
    property: G-REM7RWJTVV

markdown_extensions:
  - toc:
      permalink: true

nav:
  - Home: 
    - index.md
  - Saltbox:
      - Install:
        - saltbox/install/basics.md
        - saltbox/install/prerequisites.md
        - saltbox/install/install.md
      - Backup/Restore:
        - saltbox/backup/backup.md
        - saltbox/backup/restore.md
  - Community:
      - community/basics.md
  - Apps:
      - apps/radarr.md
      - apps/sonarr.md
  - FAQ:
      - faq/faq.md
  - Advanced:
      - advanced/example.md

copyright: Copyright &copy; 2021 Saltbox
