site_name: docs.saltbox.dev
site_url: https://docs.saltbox.dev/
site_author: salty
site_description: Saltbox is an Ansible-based solution for rapidly deploying a Docker containerized cloud media server.

repo_name: docs
repo_url: https://github.com/saltyorg/docs

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.tracking
    - navigation.instant
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    
plugins:
  - search:
      lang: en

extra:
  generator: false
  social:
  - icon: fontawesome/solid/heart
    link: 'https://github.com/sponsors/saltydk'
    name: Donate
  - icon: fontawesome/brands/discord
    link: 'https://discord.gg/ugfKXpFND8'
    name: Discord
  - icon: fontawesome/brands/github
    link: 'https://github.com/saltyorg/Saltbox'
    name: GitHub

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - admonition
  - attr_list
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Saltbox:
      - Basics: saltbox/basics/basics.md
      - Prerequisites: saltbox/prerequisites/prerequisites.md
      - Inventory: saltbox/inventory/index.md
      - Install: saltbox/install/install.md
      - Backup/Restore:
        - Settings: saltbox/backup/settings.md
        - Backup: saltbox/backup/backup.md
        - Restore: saltbox/backup/restore.md
  - Community:
      - Basics: community/basics.md
  - Apps:
      - cloudplow: apps/cloudplow.md
      - emby: apps/emby.md
      - jackett: apps/jackett.md
      - lidarr: apps/lidarr.md
      - nzbget: apps/nzbget.md
      - nzbhydra2: apps/nzbhydra2.md
      - organizr: apps/organizr.md
      - overseerr: apps/overseerr.md
      - plex: apps/plex.md
      - portainer: apps/portainer.md
      - radarr: apps/radarr.md
      - rutorrent: apps/rutorrent.md
      - sabnzbd: apps/sabnzbd.md
      - sonarr: apps/sonarr.md
      - sstv: apps/sstv.md
      - tautulli: apps/tautulli.md
  - FAQ: faq/faq.md
  - Advanced:
      - advanced/index.md
      - ZeroSSL: advanced/zerossl.md
  - Reference:
      - Server: reference/server.md
      - Domain Name: reference/domain.md
      - Cloud Storage: reference/cloud.md
      - Plex Account: reference/plex.md
      - Media Sources: reference/usenet-torrent.md
      - Ports: reference/ports.md


copyright: Copyright &copy; 2021 Saltbox
