site_name: Saltbox Documentation
site_url: https://docs.saltbox.dev/
site_author: salty
site_description: Saltbox is an Ansible-based solution for rapidly deploying a Docker containerized cloud media server.

repo_name: Saltbox
repo_url: https://github.com/saltyorg/Saltbox

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    - navigation.top
    - toc.integrate
  language: en
  palette:
    - scheme: default
      primary: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    

extra:
  generator: false
  social:
  - icon: fontawesome/solid/heart
    link: 'https://github.com/saltyorg/Saltbox/blob/master/DONATIONS.md'
    name: Donate
  - icon: fontawesome/brands/discord
    link: 'https://discord.saltbox.dev'
    name: Discord
  - icon: fontawesome/brands/github
    link: 'https://github.com/saltyorg'
    name: GitHub

markdown_extensions:
  - toc:
      permalink: true

nav:
  - Home: 'index.md'
  - Installation:
    - installation/index.md
    - installation/basics.md

copyright: Copyright &copy; 2021 Saltbox
